### ISSUE TITLE
ModuleNotFoundError: No module named 'shapely.lib'

### ISSUE THREAD

**Issue by Pizhlo** [pegler/pytzwhere#61]
I faced this error when initialize tzwhere:

```
Traceback (most recent call last):
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\controller.py", line 15, in <module>
    import records
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\records\__init__.py", line 3, in <module>
    from .main import get_records, delete_record, make_records_handlers, make_record_text, check_records
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\records\main.py", line 10, in <module>
    from scheduler import make_cron, make_interval, make_date
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\scheduler\__init__.py", line 1, in <module>
    from .main import make_cron, make_interval, make_date
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\scheduler\main.py", line 8, in <module>
    from users import get_timezone
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\users\__init__.py", line 3, in <module>
    from .location import set_timezone, get_timezone
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\users\location.py", line 4, in <module>
    from tzwhere import tzwhere
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\venv\lib\site-packages\tzwhere\tzwhere.py", line 20, in <module>
    import shapely.geometry as geometry
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\venv\lib\site-packages\shapely\__init__.py", line 17, in <module>
    from .lib import GEOSException  # NOQA
ModuleNotFoundError: No module named 'shapely.lib'
```

My python version:

```
(venv) C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder>python 
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

Does anybody know how to solve it?

**Comment by utapyngo** [comment]
`pip install shapely==1.8.5.post1`

**Comment by IsaiasCruzFlatMx** [comment]
@Pizhlo did you figure out the solution?
